package modelo;

public enum Adicionais {
    AR_CONDICIONADO, DIRECAO_HIDRAULICA, CENTRAL_MULTIMIDIA,
    SISTEMA_SOCORRO, SISTEMA_DE_COLISAO, CAMARA_RE,
    BANCOS_DE_COURO, VIDROS_ELETRICOS, FAROL_DE_NEBLINA,
    PILOTO_AUTOMATICO
}
